# File: .github/workflows/pages.yml

name: Deploy GitHub Pages

on:
  push:
    branches: [main]  # Make sure your main branch is named 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML files
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'  # use './' if your index.html is in root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
